export const TOKENS = {
  Prisma: Symbol('Prisma'),
  Redis: Symbol('Redis'),
  PrismaContext: Symbol('PrismaContext'),
  Clock: Symbol('Clock'),
  IdGenerator: Symbol('IdGenerator'),
  UnitOfWork: Symbol('UnitOfWork'),
  OrderRepository: Symbol('OrderRepository'),
  SectorCatalogRepository: Symbol('SectorCatalogRepository'),
  SectorInventoryRepository: Symbol('SectorInventoryRepository'),
  CreateOrderUseCase: Symbol('CreateOrderUseCase'),
  SignatureVerifier: Symbol('SignatureVerifier'),
  WebhookEventRepository: Symbol('WebhookEventRepository'),
  PaymentEventQueue: Symbol('PaymentEventQueue'),
  ReceiveWebhookUseCase: Symbol('ReceiveWebhookUseCase'),
} as const;